spring:
  application:
    name: springBasic
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 4000
      validation-timeout: 3000
      idle-timeout: 160000
      max-lifetime: 175000
      minimum-idle: 5
      maximum-pool-size: 1000
      pool-name: BaseHikariPool

token:
  expire:
    # 5분
    time: 300000
  secret : thisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkeythisissecretkey